# Data Cleaning

In [96]:
# Importing required libraries. 
import os
import pandas as pd

In [97]:
# File check
folder_path = "Raw_Dataset"
files = os.listdir(folder_path)
for file in files:
    print(file)

Customers.csv
Data_Dictionary.csv
Exchange_Rates.csv
Products.csv
Sales.csv
Stores.csv

# 1. Sales.csv

In [18]:
# Loading the file 
Sales = pd.read_csv("Raw_Dataset/Sales.csv")

In [19]:
# Check 1st 5 rows
Sales.head(5)

,Order Number,Line Item,Order Date,Delivery Date,CustomerKey,StoreKey,ProductKey,Quantity,Currency Code
0,366000,1,1/1/2016,NaN,265598,10,1304,1,CAD
1,366001,1,1/1/2016,1/13/2016,1269051,0,1048,2,USD
2,366001,2,1/1/2016,1/13/2016,1269051,0,2007,1,USD
3,366002,1,1/1/2016,1/12/2016,266019,0,1106,7,CAD
4,366002,2,1/1/2016,1/12/2016,266019,0,373,1,CAD

In [20]:
# Check Sample rows 
Sales.sample(5)

,Order Number,Line Item,Order Date,Delivery Date,CustomerKey,StoreKey,ProductKey,Quantity,Currency Code
15553,1115002,3,1/19/2018,NaN,1434399,45,1657,6,USD
18408,1235003,1,5/19/2018,5/25/2018,1924622,0,93,1,USD
7107,737001,1,1/6/2017,NaN,730203,28,641,1,EUR
43852,1736004,1,10/2/2019,NaN,1469753,44,1484,3,USD
3669,593004,7,8/15/2016,NaN,451559,24,187,5,EUR

In [21]:
# Check the data type , non null count
Sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 62884 entries, 0 to 62883
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order Number   62884 non-null  int64
 1   Line Item      62884 non-null  int64
 2   Order Date     62884 non-null  str
 3   Delivery Date  13165 non-null  str
 4   CustomerKey    62884 non-null  int64
 5   StoreKey       62884 non-null  int64
 6   ProductKey     62884 non-null  int64
 7   Quantity       62884 non-null  int64
 8   Currency Code  62884 non-null  str
dtypes: int64(6), str(3)
memory usage: 4.3 MB

In [22]:
# Check all column headers 
Sales.columns

Index(['Order Number', 'Line Item', 'Order Date', 'Delivery Date',
       'CustomerKey', 'StoreKey', 'ProductKey', 'Quantity', 'Currency Code'],
      dtype='str')

In [23]:
# Renaming the columns
# Normalize the column headers to snake case. 
Sales=Sales.rename(columns={
    'Order Number':'order_number',
    'Line Item':'line_item',
    'Order Date':'order_date',
    'Delivery Date':'delivery_date',
    'CustomerKey' : 'customer_key',
    'StoreKey': 'store_key',
    'ProductKey' : 'product_key',
    'Currency Code':'currency_code',
    'Quantity':'quantity'
})

In [24]:
Sales.columns

Index(['order_number', 'line_item', 'order_date', 'delivery_date',
       'customer_key', 'store_key', 'product_key', 'quantity',
       'currency_code'],
      dtype='str')

In [25]:
# Fixing the data types of columns 
Sales['order_date'] = pd.to_datetime(Sales['order_date'],errors='coerce') # str --> datetime
Sales['delivery_date'] = pd.to_datetime(Sales['delivery_date'],errors='coerce')  # str --> datetime

In [26]:
# Detecting nulls 
Sales.isnull().sum()

order_number         0
line_item            0
order_date           0
delivery_date    49719
customer_key         0
store_key            0
product_key          0
quantity             0
currency_code        0
dtype: int64

# 2. Customers.csv

In [108]:
# Loading the file
Customers = pd.read_csv("Raw_Dataset/Customers.csv",encoding="latin1",keep_default_na=False)

In [109]:
# Check 1st 5 rows 
Customers.head(5)

,CustomerKey,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday
0,301,Female,Lilly Harding,WANDEARAH EAST,SA,South Australia,5523,Australia,Australia,7/3/1939
1,325,Female,Madison Hull,MOUNT BUDD,WA,Western Australia,6522,Australia,Australia,9/27/1979
2,554,Female,Claire Ferres,WINJALLOK,VIC,Victoria,3380,Australia,Australia,5/26/1947
3,786,Male,Jai Poltpalingada,MIDDLE RIVER,SA,South Australia,5223,Australia,Australia,9/17/1957
4,1042,Male,Aidan Pankhurst,TAWONGA SOUTH,VIC,Victoria,3698,Australia,Australia,11/19/1965

In [110]:
# Check sample rows 
Customers.sample(5)

,CustomerKey,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday
2989,401785,Female,Katrin Eiffel,Niederstotzingen,BW,Baden-Württemberg,89168,Germany,Europe,5/14/1994
6136,849113,Male,Esli Tip,Weesp,NH,Noord-Holland,1382 VG,Netherlands,Europe,2/10/1963
3133,421034,Male,Alexander Baumgaertner,Viersen Rahser,NW,Nordrhein-Westfalen,41748,Germany,Europe,7/30/1993
2016,273661,Female,Valerie Oddo,Fillmore,SK,Saskatchewan,S4P 3Y2,Canada,North America,6/21/1952
2406,326924,Female,Rebecca Bennett,Torrington,AB,Alberta,T0M 2B0,Canada,North America,8/30/1966

In [111]:
# Inspect Column names,  Data type and non null count
Customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 15266 entries, 0 to 15265
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerKey  15266 non-null  int64
 1   Gender       15266 non-null  str
 2   Name         15266 non-null  str
 3   City         15266 non-null  str
 4   State Code   15266 non-null  str
 5   State        15266 non-null  str
 6   Zip Code     15266 non-null  str
 7   Country      15266 non-null  str
 8   Continent    15266 non-null  str
 9   Birthday     15266 non-null  str
dtypes: int64(1), str(9)
memory usage: 1.2 MB

In [112]:
# Fixing column header
# Normalizng to snake case 
Customers = Customers.rename(columns={
    'CustomerKey' : 'customer_key',
    'Gender': 'gender',
    'Name':'name',
    'City':'city',
    'State Code': 'state_code',
    'State' : 'state',
    'Zip Code':'zip_code',
    'Country':'country',
    'Continent':'continent',
    'Birthday':'customer_dob'
})

In [113]:
# Ensure column names 
Customers.columns

Index(['customer_key', 'gender', 'name', 'city', 'state_code', 'state',
       'zip_code', 'country', 'continent', 'customer_dob'],
      dtype='str')

In [114]:
# Fixing data type 
Customers['customer_dob']=pd.to_datetime(Customers['customer_dob'],errors='coerce') # str --> datetime

In [115]:
# Inspecting Info 
Customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 15266 entries, 0 to 15265
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   customer_key  15266 non-null  int64
 1   gender        15266 non-null  str
 2   name          15266 non-null  str
 3   city          15266 non-null  str
 4   state_code    15266 non-null  str
 5   state         15266 non-null  str
 6   zip_code      15266 non-null  str
 7   country       15266 non-null  str
 8   continent     15266 non-null  str
 9   customer_dob  15266 non-null  datetime64[us]
dtypes: datetime64[us](1), int64(1), str(8)
memory usage: 1.2 MB

In [116]:
# Checking if nulls exist
Customers.isnull().sum()

customer_key    0
gender          0
name            0
city            0
state_code      0
state           0
zip_code        0
country         0
continent       0
customer_dob    0
dtype: int64

In [117]:
Customers.loc[Customers['state_code'].isnull(),['state_code','state']]

Empty DataFrame
Columns: [state_code, state]
Index: []

In [118]:
# Checking for duplicates 
Customers.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
15261    False
15262    False
15263    False
15264    False
15265    False
Length: 15266, dtype: bool

# 3. Exchange Rate

In [119]:
# Loading the file
Exchange_Rates = pd.read_csv("Raw_Dataset/Exchange_Rates.csv")

In [120]:
# Checking the first few rows 
Exchange_Rates.head()

       Date Currency  Exchange
0  1/1/2015      USD    1.0000
1  1/1/2015      CAD    1.1583
2  1/1/2015      AUD    1.2214
3  1/1/2015      EUR    0.8237
4  1/1/2015      GBP    0.6415

In [121]:
# Checking sample rows 
Exchange_Rates.sample(5)

            Date Currency  Exchange
900    6/30/2015      USD    1.0000
8961  11/28/2019      CAD    1.3289
4218   4/23/2017      EUR    0.9348
9330   2/10/2020      USD    1.0000
5648    2/3/2018      EUR    0.8005

In [122]:
# Checking column headers  , data type , non null count
Exchange_Rates.info()

<class 'pandas.DataFrame'>
RangeIndex: 11215 entries, 0 to 11214
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      11215 non-null  str
 1   Currency  11215 non-null  str
 2   Exchange  11215 non-null  float64
dtypes: float64(1), str(2)
memory usage: 263.0 KB

In [123]:
# Normalizing the column names to snake case
Exchange_Rates = Exchange_Rates.rename(columns={
    'Date':'date',
    'Currency':'currency_code',
    'Exchange':'exchange_rate'
})

In [124]:
# Ensuring column headers
Exchange_Rates.columns

Index(['date', 'currency_code', 'exchange_rate'], dtype='str')

In [125]:
# Fixing the data types 
Exchange_Rates['date'] = pd.to_datetime(Exchange_Rates['date'],errors='coerce')

# 4. Products

In [126]:
Products = pd.read_csv("Raw_Dataset/Products.csv")

In [127]:
Products.head(5)

,ProductKey,Product Name,Brand,Color,Unit Cost USD,Unit Price USD,SubcategoryKey,Subcategory,CategoryKey,Category
0,1,Contoso 512MB MP3 Player E51 Silver,Contoso,Silver,$6.62,$12.99,101,MP4&MP3,1,Audio
1,2,Contoso 512MB MP3 Player E51 Blue,Contoso,Blue,$6.62,$12.99,101,MP4&MP3,1,Audio
2,3,Contoso 1G MP3 Player E100 White,Contoso,White,$7.40,$14.52,101,MP4&MP3,1,Audio
3,4,Contoso 2G MP3 Player E200 Silver,Contoso,Silver,$11.00,$21.57,101,MP4&MP3,1,Audio
4,5,Contoso 2G MP3 Player E200 Red,Contoso,Red,$11.00,$21.57,101,MP4&MP3,1,Audio

In [128]:
Products.sample(5)

,ProductKey,Product Name,Brand,Color,Unit Cost USD,Unit Price USD,SubcategoryKey,Subcategory,CategoryKey,Category
1789,1790,MGS Dungeon Siege: Legends of Aranna 2009 E146,Tailspin Toys,Silver,$21.92,$43.00,702,Download Games,7,Games and Toys
2265,2266,WWI Wall Lamp E215 Blue,Wide World Importers,Blue,$61.17,$119.99,806,Lamps,8,Home Appliances
682,683,Proseware Ink Jet Wireless All-In-One Printer ...,Proseware,Grey,$59.32,$129.00,306,"Printers, Scanners & Fax",3,Computers
418,419,Adventure Works Desktop PC1.80 ED180 Silver,Adventure Works,Silver,$188.13,$369.00,303,Desktops,3,Computers
2497,2498,Contoso Phone Tough Skin Case E140 Black,Contoso,Black,$12.09,$23.72,505,Cell phones Accessories,5,Cell phones

In [129]:
Products.info()

<class 'pandas.DataFrame'>
RangeIndex: 2517 entries, 0 to 2516
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ProductKey      2517 non-null   int64
 1   Product Name    2517 non-null   str
 2   Brand           2517 non-null   str
 3   Color           2517 non-null   str
 4   Unit Cost USD   2517 non-null   str
 5   Unit Price USD  2517 non-null   str
 6   SubcategoryKey  2517 non-null   int64
 7   Subcategory     2517 non-null   str
 8   CategoryKey     2517 non-null   int64
 9   Category        2517 non-null   str
dtypes: int64(3), str(7)
memory usage: 196.8 KB

In [130]:
# Renaming columns
Products = Products.rename(columns={
    'ProductKey' : 'product_key',
    'Product Name':'product_name',
    'Brand': 'brand',
    'Color':'color',
    'Unit Cost USD':'unit_cost_usd',
    'Unit Price USD':'unit_price_usd',
    'SubcategoryKey':'subcategory_key',
    'Subcategory':'subcategory',
    'CategoryKey':'category_key',
    'Category':'category'
})

In [131]:
Products.columns

Index(['product_key', 'product_name', 'brand', 'color', 'unit_cost_usd',
       'unit_price_usd', 'subcategory_key', 'subcategory', 'category_key',
       'category'],
      dtype='str')

In [132]:
Products.dtypes

product_key        int64
product_name         str
brand                str
color                str
unit_cost_usd        str
unit_price_usd       str
subcategory_key    int64
subcategory          str
category_key       int64
category             str
dtype: object

In [133]:
# Removing Special characters from column
Products['unit_cost_usd'] = Products['unit_cost_usd'].str.replace(',','')
Products['unit_cost_usd'] = Products['unit_cost_usd'].str.replace('$','',regex=False)

Products['unit_price_usd'] = Products['unit_price_usd'].str.replace(',','')
Products['unit_price_usd'] = Products['unit_price_usd'].str.replace('$','',regex=False)

In [134]:
Products.head()

,product_key,product_name,brand,color,unit_cost_usd,unit_price_usd,subcategory_key,subcategory,category_key,category
0,1,Contoso 512MB MP3 Player E51 Silver,Contoso,Silver,6.62,12.99,101,MP4&MP3,1,Audio
1,2,Contoso 512MB MP3 Player E51 Blue,Contoso,Blue,6.62,12.99,101,MP4&MP3,1,Audio
2,3,Contoso 1G MP3 Player E100 White,Contoso,White,7.40,14.52,101,MP4&MP3,1,Audio
3,4,Contoso 2G MP3 Player E200 Silver,Contoso,Silver,11.00,21.57,101,MP4&MP3,1,Audio
4,5,Contoso 2G MP3 Player E200 Red,Contoso,Red,11.00,21.57,101,MP4&MP3,1,Audio

In [135]:
# Fixing data types
Products['unit_cost_usd']  =  Products['unit_cost_usd'].astype('float')
Products['unit_price_usd']  =  Products['unit_price_usd'].astype('float')

In [136]:
Products.head(5)

,product_key,product_name,brand,color,unit_cost_usd,unit_price_usd,subcategory_key,subcategory,category_key,category
0,1,Contoso 512MB MP3 Player E51 Silver,Contoso,Silver,6.62,12.99,101,MP4&MP3,1,Audio
1,2,Contoso 512MB MP3 Player E51 Blue,Contoso,Blue,6.62,12.99,101,MP4&MP3,1,Audio
2,3,Contoso 1G MP3 Player E100 White,Contoso,White,7.40,14.52,101,MP4&MP3,1,Audio
3,4,Contoso 2G MP3 Player E200 Silver,Contoso,Silver,11.00,21.57,101,MP4&MP3,1,Audio
4,5,Contoso 2G MP3 Player E200 Red,Contoso,Red,11.00,21.57,101,MP4&MP3,1,Audio

In [137]:
Products.dtypes

product_key          int64
product_name           str
brand                  str
color                  str
unit_cost_usd      float64
unit_price_usd     float64
subcategory_key      int64
subcategory            str
category_key         int64
category               str
dtype: object

In [138]:
Products.describe().round(1)

,product_key,unit_cost_usd,unit_price_usd,subcategory_key,category_key
count,2517.0,2517.0,2517.0,2517.0,2517.0
mean,1259.0,147.7,356.8,491.8,4.9
std,726.7,184.4,494.1,229.9,2.3
min,1.0,0.5,1.0,101.0,1.0
25%,630.0,32.2,69.0,305.0,3.0
50%,1259.0,86.7,200.0,406.0,4.0
75%,1888.0,184.0,410.0,801.0,8.0
max,2517.0,1060.2,3200.0,808.0,8.0

In [139]:
Products.sample(10)

,product_key,product_name,brand,color,unit_cost_usd,unit_price_usd,subcategory_key,subcategory,category_key,category
100,101,WWI Wireless Bluetooth Stereo Headphones M170 ...,Wide World Importers,Pink,55.18,120.00,106,Bluetooth Headphones,1,Audio
750,751,Contoso Desktop Alternative Bundle E200 Black,Contoso,Black,5.86,11.50,308,Computers Accessories,3,Computers
392,393,WWI Laptop16 M0160 Black,Wide World Importers,Black,275.46,599.00,301,Laptops,3,Computers
1377,1378,Contoso 4-Line Expandable Cordless Phone Syste...,Contoso,White,10.12,22.00,501,Home & Office Phones,5,Cell phones
1847,1848,NT Washer & Dryer 25.5in M2550 White,Northwind Traders,White,915.08,1989.90,801,Washers & Dryers,8,Home Appliances
1714,1715,MGS Shadow-run M230,Tailspin Toys,White,32.25,70.13,702,Download Games,7,Games and Toys
440,441,WWI Desktop PC1.80 E1800 Brown,Wide World Importers,Brown,117.21,229.90,303,Desktops,3,Computers
1748,1749,MGS Bicycle Board Games X500,Tailspin Toys,Grey,36.11,109.00,702,Download Games,7,Games and Toys
2094,2095,Contoso Water Heater 7.2GPM X1800 Green,Contoso,Green,488.70,1475.00,804,Water Heaters,8,Home Appliances
2329,2330,Litware Wall Lamp E2015 Silver,Litware,Silver,61.17,119.99,806,Lamps,8,Home Appliances

# 5. Stores

In [3]:
# Loading the file
import pandas as pd
Stores = pd.read_csv("Raw_Dataset/Stores.csv")

In [4]:
# Checking the first few rows 
Stores.head()

   StoreKey    Country                         State  Square Meters  Open Date
0         1  Australia  Australian Capital Territory          595.0   1/1/2008
1         2  Australia            Northern Territory          665.0  1/12/2008
2         3  Australia               South Australia         2000.0   1/7/2012
3         4  Australia                      Tasmania         2000.0   1/1/2010
4         5  Australia                      Victoria         2000.0  12/9/2015

In [5]:
# Check sample rows 
Stores.sample(5)

    StoreKey        Country                   State  Square Meters Open Date
15        16         France                Limousin          385.0  6/3/2010
24        25        Germany  Mecklenburg-Vorpommern         1610.0  1/1/2010
28        29          Italy                    Enna         1000.0  1/1/2008
45        46  United States                Delaware         1015.0  8/8/2012
48        49  United States                    Iowa         2000.0  6/3/2018

In [6]:
# Check Column names ,data type and non null count
Stores.info()

<class 'pandas.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   StoreKey       67 non-null     int64
 1   Country        67 non-null     str
 2   State          67 non-null     str
 3   Square Meters  66 non-null     float64
 4   Open Date      67 non-null     str
dtypes: float64(1), int64(1), str(3)
memory usage: 2.7 KB

In [7]:
# Fix the column headers 
# Normalize to snake case

Stores = Stores.rename(columns={
    'StoreKey':'store_key',
    'Country':'country',
    'State':'state',
    'Square Meters':'square_meters',
    'Open Date':'open_date'
})

In [8]:
Stores.dtypes

store_key          int64
country              str
state                str
square_meters    float64
open_date            str
dtype: object

In [9]:
# Fixing data types 
Stores['open_date'] = pd.to_datetime(Stores['open_date'],errors='coerce') # str --> datetime

In [10]:
Stores.sample(5)

,store_key,country,state,square_meters,open_date
26,27,Germany,Sachsen-Anhalt,2000.0,2008-08-08
20,21,Germany,Freie Hansestadt Bremen,560.0,2018-06-03
14,15,France,La Réunion,400.0,2015-01-01
60,61,United States,South Carolina,2000.0,2012-12-15
10,11,Canada,Yukon,1210.0,2009-06-03

In [148]:
Sales.to_csv("Cleaned_Dataset/Sales.csv")
Products.to_csv("Cleaned_Dataset/Products.csv")
Stores.to_csv("Cleaned_Dataset/Stores.csv")
Exchange_Rates.to_csv("Cleaned_Dataset/Exchange_Rates.csv")
Customers.to_csv("Cleaned_Dataset/Customers.csv")

In [12]:
Stores.isnull().sum()

store_key        0
country          0
state            0
square_meters    1
open_date        0
dtype: int64

In [15]:
Stores.loc[Stores['store_key']==0,:]

    store_key country   state  square_meters  open_date
66          0  Online  Online            NaN 2010-01-01